### ISSUE TITLE
benchmark_division_performance can't be found in isbi_utils.py

### ISSUE THREAD

**Issue by SBassler** [vanvalenlab/deepcell-tracking#117]
Dear VanValen lab team,
Thanks for the great work you do!
I followed your "Training and Tracking with GNNs" notebook but at the last step:

import json
from deepcell_tracking.isbi_utils import benchmark_division_performance
results = benchmark_division_performance(gt_trk_path, res_file_path)

I get the following error:
ImportError: cannot import name 'benchmark_division_performance' from 'deepcell_tracking.isbi_utils'

I checked and indeed, the isbi_utils.py file does not contain 'benchmark_division_performance'.
Best wishes,
Stefan

**Comment by msschwartz21** [comment]
Hi Stefan,

The notebook has fallen a bit out of date, but you should be able to replace `from deepcell_tracking.isbi_utils import benchmark_division performance` with `from deepcell_tracking.metrics import benchmark_tracking_performance`. I will also look into updating the notebook and I'll let you know when the new version is available.

**Comment by SBassler** [comment]
Thank you very much for the quick response and keep up the cool work!

**Comment by SBassler** [comment]
Unfortunately, benchmark_division_performance is still not defined.
Best wishes,
Stefan

NameError: name 'benchmark_division_performance' is not defined
￼

**Comment by SBassler** [comment]
Nevermind, I managed by importing deepcell_tracking once more, thanks!
