### ISSUE TITLE
Images must be normalized prior to use in the cell tracker

### ISSUE THREAD

**Issue by vanvalen** [vanvalenlab/deepcell-tracking#28]
Given that the cell tracker was trained on normalized images, this should be mentioned in the readme

**Comment by vanvalen** [comment]
Ideally, this would be built in. Perhaps we should write an applications object for this, just like we've done for the segmentation.

**Comment by willgraf** [comment]
This issue has been resolved in vanvalenlab/deepcell-tf#444 by wrapping the pre-processing into an application function.

Since the pre-processing is a requirement of the model and not the tracking algorithm, there are no required changes in this repository.
