### ISSUE TITLE
Tracking models

### ISSUE THREAD

**Issue by Ciro1990** [vanvalenlab/deepcell-tracking#93]
Hi there,

first of all thanks for developing deepcell and deepcell-tracking and for the extensive explanation in the notebooks. I was wondering if there are some available tracking model available that I could test before training my own model.

Thanks in advance!
Ciro

**Comment by msschwartz21** [comment]
Hi Ciro,

Pretrained models are available through the deepcell.org and `deepcell.applications`. You can directly run your data through the Caliban tracking pipeline at https://deepcell.org/predict. Alternatively take a look at the [Nuclear Application Notebook](https://github.com/vanvalenlab/deepcell-tf/blob/master/notebooks/applications/Nuclear-Application.ipynb) which has a section on cell tracking that loads a pretrained model from `deepcell.applications`.
